services:
  weather_api:
    build: ./weather_api
    volumes:
     - .:/weather_code
  events_api:
    build: events_api
    volumes:
      - .:/events_code
  web_app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/web_app
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
